postgres:
  port: 5432
  host: pgdb
  user: postgres
  pass: qwerty123
  name: postgres
  sslmode: disable

telegram:
  token: 5038550239:AAEa0QVQKFo2QFxTUukvt4kfkIwzEuVmYMM
  channel: dmtfcc

instagram:
  username: zupka228
  password: zupka2288
  userparse: dmtfccollege

parser:
  minutes: 60