postgres:
  port: 5432
  host: pgdb
  user: postgres
  pass: qwerty123
  name: postgres
  sslmode: disable

telegram:
  token: token
  channel: channel # channel where the bot will send photos (without @)

instagram:
  username: username
  password: password
  userparse: userparse # whose username must be parsed (without @)

parser:
  minutes: 60